NCCC_listed_merchant:
#模擬資料，實際資料以NCCC提供為主
  - '麥當勞'
  - '肯德基'
  - '真芳碳烤吐司'
  - '85度C'
  - 'ＣｏＣｏ都可'
  - '清心福全'
  - '可不可熟成紅茶'
  - '八方雲集'
  - 'SUBWAY'
  - 'SUKIYA'
  - 'Qburger'
  - 'CREMIA北海道冰淇淋之神'
  - '七盞茶'
  - '漢堡王'
  - '包子商行'
  - '鬍鬚張'
  - '50嵐'
  - '拿坡里'
  - '三商其他餐飲品牌'
  - '梁社漢排骨'
  - '呷尚寶'
  - '頂呱呱'
  - '麥味登'
  - '萬波島嶼紅茶'
  - '樂田麵包屋'
  - '五桐號'
  - '德國農莊茶烘焙館'
  - 'REAL真烘焙坊'
  - '樂法'
  - '季緣'
  - '三商巧福'
  - '牧牧'
  - '良本崎'
  - '米哥烘焙坊'
  - '潮味決'
  - '一沐日'
